nome=(input("qual seu nome?:"))
idade=int(input("qual a sua idade?:"))
altura=bool(input("qual altura?:"))
peso=(input("qual seu peso?:"))
print("olá!", nome,",sua idade é",idade,"e seu peso é",peso,"você tem qualidades de uma vida saudavel")
